---
# yamllint disable rule:empty-lines

{# import macros to use in this template #}
{% import "macros/macros.j2" as macros %}

{# define test features (single-cluster test jobs) that can be requested by the Makefile via context variables #}
{% set requested_features = {'s3': s3, 'gs': gs, 'abfss': abfss, 'wasbs': wasbs, 'minio': minio, 'hdp2': hdp2, 'hdp3': hdp3, 'cdh': cdh, 'jdk11': jdk11, 'load': load} %}
{# define common test features (single-cluster test jobs) that are all requestable features other than load testing #}
{% set common_features = requested_features.keys() | list | reject('eq','load') %}

{# define whether multinode testing is requested for given EL OS versions #}
{% set requested_multi = {'7': multinode_el7, '8': multinode_el8, '9': multinode_el9} %}

{#
# ======================================================================
# BUILD and TEST Combinations for PXF
# ======================================================================

# gp_ver        : major Greenplum version
# build_os      : the name of the OS used to build PXF artifacts
# test_os       : the name of the OS used to test  PXF artifacts
# os_ver        : the version of the OS
# test_fdw      : whether to test PXF FDW extension in this configuration
# test_file     : whether to test PXF with FILE protocol in this configuration
# test_cli      : whether to test PXF CLI functionality in this configuration
# test_multi    : whether to test PXF against multi-node Hadoop clusters in this configuration
# test_features : an array of features to test PXF with in this configuration
#
# when iterating over the entries, use the following pattern:
# {% call(x) macros.for_each_config(build_test_pxf_combinations) %}
#     <do whatever rendering you need for a combination, can use {% include '.../some-template.yml' %} >
# {% endcall %}
#}

{% set build_test_pxf_combinations = [
    {'gp_ver': '5', 'build_os': 'centos', 'test_os': 'centos', 'os_ver': '7',     'test_fdw': false, 'test_file': false, 'test_cli': false, 'test_multi': false, 'test_features': []},
    {'gp_ver': '6', 'build_os': 'centos', 'test_os': 'centos', 'os_ver': '7',     'test_fdw': false, 'test_file': true , 'test_cli': false, 'test_multi': true , 'test_features': common_features},
    {'gp_ver': '6', 'build_os': 'rocky' , 'test_os': 'rocky' , 'os_ver': '8',     'test_fdw': true , 'test_file': false, 'test_cli': false, 'test_multi': false, 'test_features': []},
    {'gp_ver': '6', 'build_os': 'rocky' , 'test_os': 'rocky' , 'os_ver': '9',     'test_fdw': false, 'test_file': false, 'test_cli': false, 'test_multi': true , 'test_features': []},
    {'gp_ver': '6', 'build_os': 'centos', 'test_os': 'oel'   , 'os_ver': '7',     'test_fdw': false, 'test_file': false, 'test_cli': false, 'test_multi': false, 'test_features': []},
    {'gp_ver': '6', 'build_os': 'ubuntu', 'test_os': 'ubuntu', 'os_ver': '18.04', 'test_fdw': false, 'test_file': false, 'test_cli': false, 'test_multi': false, 'test_features': []},
    {'gp_ver': '7', 'build_os': 'rocky' , 'test_os': 'rocky' , 'os_ver': '8',     'test_fdw': true , 'test_file': false, 'test_cli': true , 'test_multi': true , 'test_features': ['load']},
    {'gp_ver': '7', 'build_os': 'rocky' , 'test_os': 'rocky' , 'os_ver': '9',     'test_fdw': false, 'test_file': false, 'test_cli': false, 'test_multi': false, 'test_features': []}] %}


{# define supported clouds that have their own 'protocols' #}
{% set clouds = ['s3', 'gs', 'abfss', 'wasbs', 'minio'] %}

{# define distros we use for singlecluster setup #}
{% set distros = ['hdp2', 'hdp3', 'cdh'] %}

{# define default distro and impersonation for all test jobs #}
{% set default_distro = 'hdp2' %}
{% set default_impers = 'true' %}

{% set gp_num_versions = { '5': num_gpdb5_versions, '6': num_gpdb6_versions, '7': num_gpdb7_versions} %}

{# define whether CCP should be used #}
{% set use_ccp = multinode_el7 or multinode_el8 or multinode_el9 or multinode_no_impersonation or file or gp7_cli %}

{# define whether IPA should be used #}
{% set use_ipa = multinode_el7 or multinode_el8 or multinode_el9 %}

## ======================================================================
## ANCHORS
## ======================================================================
anchors:
    [[macros.anchor_destroy_dataproc(1)]]
    [[macros.anchor_destroy_dataproc(2)]]
    [[macros.anchor_destroy_cluster('gpdb')]]
    [[macros.anchor_destroy_cluster('ipa-hadoop')]]
    [[macros.anchor_gchat_notification(gchat_notification)]]

## ======================================================================
## RESOURCE TYPES
## ======================================================================
resource_types:

{% if use_ccp %}
    [[macros.resource_type_registry_image('terraform', 'gcr.io/data-gpdb-ud/terraform-resource', '0.11.15')]]
{% endif %}

{% if use_ipa %}
    [[macros.resource_type_registry_image('terraform-0.14.10', 'ljfranklin/terraform-resource', '0.14.10')]]
{% endif %}

    [[macros.resource_type_registry_image('gcs', 'gcr.io/data-gpdb-public-images/gcs-resource', '')]]

{% if gchat_notification %}
    [[macros.resource_type_registry_image('google-chat-notify-resource', 'springio/google-chat-notify-resource', '0.0.1-SNAPSHOT')]]
{% endif %}

## ======================================================================
## RESOURCES
## ======================================================================
resources:
    [[macros.resource_pxf_dependencies('build')]]
    [[macros.resource_pxf_dependencies('automation')]]

    [[macros.resource_singlecluster('hdp2')]]

{% if hdp3 %}
    [[macros.resource_singlecluster('hdp3')]]
{% endif %}

{% if cdh %}
    [[macros.resource_singlecluster('cdh')]]
{% endif %}

## ---------- Github Repos ----------
    [[macros.resource_github_repo('pxf')]]

{% if use_ccp %}
    [[macros.resource_github_repo('ccp')]]
{% endif %}

## ---------- Docker Images ----------
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% if x.test_platform != 'oel7' or oel7 %}
        {% include 'resources/pxf-test-image-tpl.yml' %}
    {% endif %}
{% endcall %}

{% if use_ccp %}
    [[macros.resource_registry_image('ccp-7-image', 'gcr.io/data-gpdb-public-images/ccp', 'latest')]]
{% endif %}

## ---------- Google Chat Notification ----------
{% if gchat_notification %}
    [[macros.resource_gchat_notification('gchat-alert', 'gchat-' ~ user ~ '-ci-webhook')]]
{% endif %}

## ---------- Greenplum Packages ----------
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% do x.update({'gp_num_versions': gp_num_versions[x.gp_ver]}) %}
    {% include 'resources/greenplum-package-tpl.yml' %}
{% endcall %}

## ---------- PXF Artifacts ----------
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% include 'resources/pxf-artifact-tpl.yml' %}
{% endcall %}

- name: gpdb7_rhel8_rpm_latest-0
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/gpdb-concourse-resources-prod-bucket-name))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: server/published/master/greenplum-db-(7.*)-rhel8-x86_64.rpm

## ---------- PXF 5 Artifact ---------------
{% if multinode_el7 %}
    [[macros.resource_pxf5_gp6_el7_artifact()]]
{% endif %}

## ---------- PXF Build Artifacts ----------
{% set gp_ver = None %}

{% for gp_ver in range(5, 8) %}
- name: pxf_gp[[gp_ver]]_tarball_rhel7
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/build-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    versioned_file: dev/[[user]]-[[branch]]/snapshots/pxf6/pxf-gp[[gp_ver]].el7.tar.gz
{% endfor %}

{% set gp_ver = 6 %}
- name: pxf_gp[[gp_ver]]_tarball_ubuntu18
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/build-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    versioned_file: dev/[[user]]-[[branch]]/snapshots/pxf6/pxf-gp[[gp_ver]]-ubuntu18.04.tar.gz
{% set gp_ver = None %}

{% for gp_ver in range(6, 7) %}
- name: pxf_gp[[gp_ver]]_tarball_rhel8
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/build-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    versioned_file: dev/[[user]]-[[branch]]/snapshots/pxf6/pxf-gp[[gp_ver]].el8.tar.gz
{% endfor %}


- name: pxf_gp7_headerfile
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/build-resources-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    versioned_file: build-dependencies/extaccess.h


- name: pxf-build-dependencies
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/build-resources-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    versioned_file: build-dependencies/pxf-build-dependencies.tar.gz

## ---------- Auxiliary Resources ----------
{% if use_ccp %}
    [[macros.resource_terraform('gpdb')]]
{% endif %}

{% if use_ipa %}
    [[macros.resource_terraform('ipa-hadoop')]]
{% endif %}

## ======================================================================
## JOBS
## ======================================================================
jobs:

## ---------- Centos 7 Swimlane ----------
{% for gp_ver in range(5, 8) %}
- name: Build PXF-GP[[gp_ver]] on RHEL7
  plan:
  - in_parallel:
    - get: pxf_src
      trigger: true
    - get: gpdb_package
      resource: gpdb[[gp_ver]]_rhel7_rpm_latest-0
    - get: gpdb[[gp_ver]]-pxf-dev-centos7-image
    - get: pxf-build-dependencies
{% if gp_ver == 7 %}
    - get: pxf_gp7_headerfile
{% endif %}
  - task: Build PXF-GP[[gp_ver]] on RHEL7
    image: gpdb[[gp_ver]]-pxf-dev-centos7-image
    file: pxf_src/concourse/tasks/build.yml
    params:
      LICENSE: ((ud/pxf/common/rpm-license))
      VENDOR: ((ud/pxf/common/rpm-vendor))
  - put: pxf_gp[[gp_ver]]_tarball_rhel7
    params:
      file: dist/pxf-gp[[gp_ver]]-*.el7.tar.gz

{# include a non-FDW test job for all OS other than OEL (unless requested in the Makefile) #}
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% if x.test_os != 'oel' or oel7 %}
        {% do x.update({'use_fdw': 'false'}) %}
        {% do x.update({'use_impers': default_impers}) %}
        {% do x.update({'target': default_distro}) %}
        {% do x.update({'distro': default_distro}) %}
        {% include 'jobs/test-tpl.yml' %}
    {% endif %}
{% endcall %}

{# include an FDW test job if supported by the swimlane #}
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% if x.test_fdw is sameas true %}
        {% do x.update({'use_fdw': 'true'}) %}
        {% do x.update({'use_impers': default_impers}) %}
        {% do x.update({'target': default_distro}) %}
        {% do x.update({'distro': default_distro}) %}
        {% include 'jobs/test-tpl.yml' %}
    {% endif %}
{% endcall %}

## ---------- Extended Feature (clouds, distros, jdk) tests ----------
{# include a non-FDW test job for all clouds if supported and requested in the Makefile #}
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {# iterate over features defined for the given swimlane #}
    {% for test_feature in x.test_features %}
        {# if the given feature is requested by the Makefile, create a non-FDW job for it #}
        {% if requested_features[test_feature] %}
            {% do x.update({'use_fdw': 'false'}) %}

            {# if the purpose of the test is to try a different distro/cloud, use it, otherwise use a default distro for the job name #}
            {% set target = test_feature if (test_feature in distros or test_feature in clouds) else default_distro %}
            {% do x.update({'target': target}) %}

            {# set the distro to use for the test job's single cluster, use default if the feature are not a distro #}
            {% set distro = test_feature if test_feature in distros else default_distro %}
            {% do x.update({'distro': distro}) %}

            {# request a no-impers job for clouds and the default distro (as basic test job is default distro with impersonation) #}
            {% set use_impers = 'false' if (test_feature in clouds or test_feature == default_distro) else 'true' %}
            {% do x.update({'use_impers': use_impers}) %}

## -- PXF GP7 REHL 8 --

  {% set gp_ver = 7 %}
- name: Build PXF-GP[[gp_ver]] on RHEL8
  plan:
    - in_parallel:
        - get: pxf_src
          trigger: true
        - get: gpdb_package
          resource: gpdb[[gp_ver]]_rhel8_rpm_latest-0
        - get: gpdb[[gp_ver]]-pxf-dev-rhel8-image
        - get: pxf-build-dependencies
    - task: Build PXF-GP[[gp_ver]] on RHEL8
      image: gpdb[[gp_ver]]-pxf-dev-rhel8-image
      file: pxf_src/concourse/tasks/build.yml
      params:
        LICENSE: ((ud/pxf/common/rpm-license))
        VENDOR: ((ud/pxf/common/rpm-vendor))
        GOOGLE_CREDENTIALS: ((ud/pxf/secrets/ccp-ci-service-account-key))
        GOOGLE_PROJECT_ID: ((ud/pxf/common/google-project-id))
        GOOGLE_ZONE: ((ud/pxf/common/google-zone))
    - put: pxf_gp[[gp_ver]]_tarball_rhel8
      params:
        file: dist/pxf-gp[[gp_ver]]-*.el8.tar.gz

- name: Test PXF-GP[[gp_ver]]-HDP2 on RHEL8
  plan:
    - in_parallel:
        - get: pxf_src
          passed: [Build PXF-GP[[gp_ver]] on RHEL8]
          trigger: true
        - get: pxf_tarball
          resource: pxf_gp[[gp_ver]]_tarball_rhel8
          passed: [Build PXF-GP[[gp_ver]] on RHEL8]
        - get: gpdb_package
          resource: gpdb[[gp_ver]]_rhel8_rpm_latest-0
          passed: [Build PXF-GP[[gp_ver]] on RHEL8]
        - get: gpdb[[gp_ver]]-pxf-dev-rhel8-image
          passed: [Build PXF-GP[[gp_ver]] on RHEL8]
        - get: pxf-automation-dependencies
        - get: singlecluster
          resource: singlecluster-hdp2
    - task: Test PXF-GP[[gp_ver]]-HDP2 on RHEL8
      file: pxf_src/concourse/tasks/test.yml
      image: gpdb[[gp_ver]]-pxf-dev-rhel8-image
      params:
        ACCESS_KEY_ID: ((tf-machine-access-key-id))
        GP_VER: [[gp_ver]]
        GROUP: gpdb,proxy,profile
SECRET_ACCESS_KEY: ((tf-machine-secret-access-key))
  {% set gp_ver = None %}

## ---------- Extended Tests ----------
{% set gp_ver = 6 %}
{% if hdp2 %}
- name: Test PXF-GP[[gp_ver]]-HDP2-NO-IMPERS on RHEL7
  plan:
  - in_parallel:
    - get: pxf_src
      passed: [Build PXF-GP[[gp_ver]] on RHEL7]
      trigger: true
    - get: pxf_tarball
      resource: pxf_gp[[gp_ver]]_tarball_rhel7
      passed: [Build PXF-GP[[gp_ver]] on RHEL7]
    - get: gpdb_package
      resource: gpdb[[gp_ver]]_rhel7_rpm_latest-0
      passed: [Build PXF-GP[[gp_ver]] on RHEL7]
    - get: gpdb[[gp_ver]]-pxf-dev-centos7-image
    - get: pxf-automation-dependencies
    - get: singlecluster
      resource: singlecluster-hdp2
  - task: Test PXF-GP[[gp_ver]]-HDP2-NO-IMPERS on RHEL7
    file: pxf_src/concourse/tasks/test.yml
    image: gpdb[[gp_ver]]-pxf-dev-centos7-image
    params:
      GP_VER: [[gp_ver]]
      IMPERSONATION: false
{% if slack_notification %}
    <<: *slack_alert
{% endif %}
{% endif %}

            {# define a feature name to go into the test job name, unless it is a test against a distro/cloud only #}
            {% set feature = test_feature if test_feature not in distros and test_feature not in clouds else '' %}
            {% do x.update({'feature': feature}) %}
            {% include 'jobs/test-tpl.yml' %}

            {# for S3 only, also include an additional impersonation job #}
            {% if test_feature == 's3' %}
                {% do x.update({'use_impers': 'true'}) %}
                {% include 'jobs/test-tpl.yml' %}
            {% endif %}

        {% endif %}
    {% endfor %}
{% endcall %}

## ---------- FILE tests -----------------
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% if x.test_file is sameas true and file %}
        {% do x.update({'distro': default_distro}) %}
        {% include 'jobs/test-file-tpl.yml' %}
    {% endif %}
{% endcall %}

## ---------- GP7 PXF CLI tests ----------
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {# for now Makefile only defines the switch for GP7 #}
    {% if x.test_cli is sameas true and x.gp_ver == '7' and gp7_cli %}
        {% include 'jobs/test-cli-tpl.yml' %}
    {% endif %}
{% endcall %}

## ---------- Multi-node tests ----------
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% if x.test_multi is sameas true and requested_multi[x.os_ver] %}
        {% do x.update({'use_fdw': 'false'}) %}
        {% do x.update({'use_impers': 'true'}) %}
        {% do x.update({'target': default_distro}) %}
        {% do x.update({'distro': default_distro}) %}
        {# include upgrade task when running on centos7 only #}
        {% set with_upgrade = 'true' if x.test_platform == 'centos7' else 'false' %}
        {% do x.update({'with_upgrade': with_upgrade}) %}
        {% include 'jobs/test-multinode-tpl.yml' %}
    {% endif %}
    {# multinode no impersonation job for now will only be for GP6 and Centos7 #}
    {% if x.test_multi is sameas true and multinode_no_impersonation and x.gp_ver == '6' and x.test_platform == 'centos7' %}
        {% do x.update({'use_fdw': 'false'}) %}
        {% do x.update({'use_impers': 'false'}) %}
        {% do x.update({'target': default_distro}) %}
        {% do x.update({'distro': default_distro}) %}
        {% do x.update({'with_upgrade': 'false'}) %}
        {% include 'jobs/test-multinode-tpl.yml' %}
    {% endif %}
{% endcall %}
