deb-pxf6-gpdb-bionic:
	echo "===> Building PXF 6 for open-gpdb for bionic <==="
	docker build -f 'package/gpdb_bionic/Dockerfile'  .

deb-pxf6-gpdb-jammy:
	echo "===> Building PXF 6 for open-gpdb for jammy <==="
	docker build -f 'package/gpdb_jammy/Dockerfile'  .

deb-pxf6-cbdb-jammy:
	echo "===> Building PXF 6 for Cloudberry for jammy <==="
	docker build -f 'package/cbdb_jammy/Dockerfile'  .
