on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'release-*' # match on release tags

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: PXF Version ${{ github.ref }}
          body: |
            ## 6.10.0 (03/04/2024)

            ### Enhancements:

            - [#1080](https://github.com/greenplum-db/pxf/pull/1080) Add support for UUID to JDBC profile
            - [#1081](https://github.com/greenplum-db/pxf/pull/1081) Add automation test cases for JDBC profile DATE_WIDE_RANGE feature
            - [#1093](https://github.com/greenplum-db/pxf/pull/1093) Bump Postgresql JDBC driver to 42.7.2
            - [#1096](https://github.com/greenplum-db/pxf/pull/1096) Add formatting for Date values

          draft: false
          prerelease: false
