on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'release-*' # match on release tags

name: Create Release

jobs:
  build_pxf_for_debian:
    strategy:
      matrix:
        target: [ 'pxf_6_bionic', 'pxf_6_jammy', 'pxf_cb_jammy' ]
    uses: ./.github/workflows/build-deb-packages.yml
    with:
        target: ${{ matrix.target }}

  build_pxf_drivers_for_debian:
    steps:
      # FIXME

  publish:
    runs-on: ubuntu-latest
    name: Upload Debian Package
    needs: [build_pxf_for_debian, build_pxf_drivers_for_debian]
    steps:
      - name: Download Debian Package
        uses: actions/download-artifact@v4
        with:
          name: ${{needs.build_debian.outputs.package_name}}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{needs.build_debian.outputs.package_name}}
